# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://thedailyportal.com
title: The Daily Portal
subtitle:  A blog for issues
author: Testy Testerson
simple_search: http://google.com/search
description:

# Default date format is "ordinal" (resulting in "July 22nd 2007")
# You can customize the format as defined in
# http://www.ruby-doc.org/core-1.9.2/Time.html#method-i-strftime
# Additionally, %o will give you the ordinal representation of the day
date_format: "ordinal"

# RSS / Email (optional) subscription links (change if using something like Feedburner)
subscribe_rss: /atom.xml

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# If publishing to a subdirectory as in http://site.com/project set 'root: /project'
root: /
permalink: /post/:year/:month/:day/:title
source: source
destination: public
plugins: plugins
code_dir: downloads/code
category_dir: blog/categories
markdown: rdiscount
pygments: false # default python pygments have been replaced by pygments.rb

paginate: 10          # Posts per page on the blog index
pagination_dir: blog  # Directory base for pagination URLs eg. /blog/page/2/
recent_posts: 5       # Posts in the sidebar Recent Posts section
excerpt_link: "Read on &rarr;"  # "Continue reading" link text at the bottom of excerpted articles

titlecase: True       # Converts page and post titles to titlecase
# current_issue: 1

current_issue: 1

jekyll_sort:
  - src: posts
    by: order
    dest: posts_sorted_by_order
  - src: posts_sorted_by_order
    group_by: issues
    dest: posts_by_issue


jekyll_models: ['issues']
jekyll_models_urls: 'rest-like'

assets:
  #
  # Pathname of the destination of generated (bundled) assets relative
  # to the destination of the root.
  #
  dirname: assets
  #
  # Base URL of assets paths.
  #
  baseurl: /assets/
  #
  # Pathnames where to find assets relative to the root of the site.
  #
  sources:
    - _assets/js
    - _assets/scss
  gzip: [ text/css, application/javascript ]

compress:
    js:   ~
    css : 'sass'